def FILE_PATH
def getFileParamFromWorkspace(fileParamName) {
    def paramsAction = currentBuild.rawBuild.getAction(ParametersAction.class);
    if (paramsAction != null) {
        for (param in paramsAction.getParameters()) {
            if (param instanceof FileParameterValue) {
                def fileParameterValue = (FileParameterValue)param
                if (fileParamName.equals(fileParameterValue.getName())) {
                    def fileItem = fileParameterValue.getFile()
                    if (fileItem instanceof org.apache.commons.fileupload.disk.DiskFileItem) {
                        def diskFileItem = (org.apache.commons.fileupload.disk.DiskFileItem)fileParameterValue.getFile()
                        def filePath = new hudson.FilePath(null, env.WORKSPACE + '/file/' + fileItem.getName())
                        def destFolder = filePath.getParent()
                        destFolder.mkdirs()
                        filePath.copyFrom(diskFileItem)
                        return 'file/' + fileItem.getName()
                    }
                }
            }
        }
    }
    return ''
}

pipeline {
  agent any
  environment {
    CREDENTAILS = credentials('example-credentials-id')
  }
  parameters {
    file(name: 'Input_File', description: 'Membership Ids file')
    choice(choices: ['qa','prod'], description: 'Environment', name: 'env')
  }
  stages {
    stage('Launch file uploader') {
        steps {
            echo "Running image pipelines-cs-file-uploader"
            script {
                FILE_PATH = "${env.WORKSPACE}/" + getFileParamFromWorkspace('Input_File')
            }
        }
    }
    stage('Build') {
      steps {
        dir("${env.WORKSPACE}/auto-renewal"){
          sh 'pwd'
          sh "python3 auto-renewal.py --username ${CREDENTAILS.USR} --password ${CREDENTAILS.PSW} --filePath ${FILE_PATH}"
        }
      }
    }
  }
}